### ISSUE TITLE
PROD SUPPORT: [Landing_page]: [should show only S138 cases]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/Oncourts_Landing_page#14]
**Expected behavior**
Landing page search should have only S138 cases on search type

**Screenshots**
I
![S138 Case](https://github.com/user-attachments/assets/6dc144ca-b406-40fb-8d94-7f35215c1ba6)

**Comment by suresh12** [comment]
@muhammed-sawad @Susmitabe Can you please try again? 
I see the following,
![image](https://github.com/user-attachments/assets/0c109a8c-9a89-40c0-97d5-99f923031d3b)
