### ISSUE TITLE
PROD SUPPORT: [Landing_page]: [Change Grievance Redressal  to Support ]

### ISSUE THREAD

**Issue by muhammed-sawad** [pucardotorg/Oncourts_Landing_page#15]
**Describe the bug**
In application landing page it is showing as Grievance Redressal 

**Expected behavior**
In application landing page instead of Grievance Redressal write "Support "

**Screenshots**
![Grievence Redressal to Support](https://github.com/user-attachments/assets/e3dfb3c6-470e-4601-81a9-6dece905f54c)

**Comment by suresh12** [comment]
@mehulseg24 Please approve

**Comment by tanmaybhateja** [comment]
Please do this change team

**Comment by muhammed-sawad** [comment]
changes not done
![image](https://github.com/user-attachments/assets/ca98f54c-922c-45e5-a974-5996ac121c4e)

**Comment by muhammed-sawad** [comment]
Showing as expected
![image](https://github.com/user-attachments/assets/2c60febe-ab64-40a0-be02-4fda57101ed6)
