### ISSUE TITLE
PROD SUPPORT:   The landing page with google form is not working

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/Oncourts_Landing_page#22]
![image](https://github.com/user-attachments/assets/e0cedaca-e92d-44d9-9ddd-e078bf421e41)

The landing page needs to have the support Google form and the overall linktree

**Comment by Ramu-kandimalla** [comment]
Landing page development done by Pratiksha Please assign to her @devarajd94

**Comment by psankhe28** [comment]
Which google form @Susmitabe ?

**Comment by devarajd94** [comment]
https://forms.gle/uCSgGiqGiMQYjjgeA

@psankhe28 please find the google form link

**Comment by muhammed-sawad** [comment]
Working as expected
**screen-recorder**
[Screencast from 30-12-24 10:35:04 PM IST.webm](https://github.com/user-attachments/assets/3ce6eef9-ce4c-4948-a5a9-5a7051f2fa5a)
