### ISSUE TITLE
PROD SUPPORT: Landing Page |Change the email address

### ISSUE THREAD

**Issue by Susmitabe** [pucardotorg/Oncourts_Landing_page#24]
![image](https://github.com/user-attachments/assets/51c1345e-9188-4f1a-a99f-1b0fcc5663cc)

Change it to -  
Correct email: oncourtkollam@keralacourts.in

**Comment by muhammed-sawad** [comment]
Showing correct mail id
**Screenshot for ref:**
![image](https://github.com/user-attachments/assets/1a203f71-7b50-45d6-8d06-52c0ff8aaf76)
